/* eslint-disable camelcase */
/* eslint-disable no-unused-vars */
export enum ErrorsEnum {
  INSTALLATION_ERROR = 'INSTALLATION_ERROR',
  CREATE_DIRS_ERROR = 'CREATE_DIRS_ERROR',
  CLONE_REPOS_ERROR = 'CLONE_REPOS_ERROR',

  BOUNTY_ERROR = 'BOUNTY_ERROR',
  DASHBOARD_ERROR = 'DASHBOARD_ERROR',
  FIREFOX_ERROR = 'FIREFOX_ERROR',
  NODE_ERROR = 'NODE_ERROR',
  POINTSDK_ERROR = 'POINTSDK_ERROR',
  UNINSTALLER_ERROR = 'UNINSTALLER_ERROR',

  DOWNLOAD_ERROR = 'DOWNLOAD_ERROR',
  FIREFOX_CONFIG_ERROR = 'FIREFOX_CONFIG_ERROR',
  LAUNCH_ERROR = 'LAUNCH_ERROR',
  STOP_ERROR = 'STOP_ERROR',
  UNPACK_ERROR = 'UNPACK_ERROR',
  UPDATE_ERROR = 'UPDATE_ERROR',

  GITHUB_ERROR = 'GITHUB_ERROR',
  TESTENV_ERROR = 'TESTENV_ERROR',
  FATAL_ERROR = 'FATAL_ERROR',
  LOCKFILE_ERROR = 'LOCKFILE_ERROR'
}
