/* eslint-disable camelcase */
/* eslint-disable no-unused-vars */
export enum ErrorsEnum {
  INSTALLATION_ERROR = 'INSTALLATION_ERROR',
  CREATE_DIRS_ERROR = 'CREATE_DIRS_ERROR',
  CLONE_REPOS_ERROR = 'CLONE_REPOS_ERROR',

  NODE_ERROR = 'NODE_ERROR',
  FIREFOX_ERROR = 'FIREFOX_ERROR',
  POINTSDK_ERROR = 'POINTSDK_ERROR',
  UNINSTALLER_ERROR = 'UNINSTALLER_ERROR',

  DOWNLOAD_ERROR = 'DOWNLOAD_ERROR',
  UNPACK_ERROR = 'UNPACK_ERROR',
  FIREFOX_CONFIG_ERROR = 'FIREFOX_CONFIG_ERROR',
}
